WITH RARE_ITEM AS (
    SELECT ITEM_INFO.ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
),
UPGRADED_ITEM AS (
    SELECT DISTINCT ITEM_TREE.ITEM_ID
    FROM RARE_ITEM, ITEM_TREE
    WHERE RARE_ITEM.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID
)

SELECT UPGRADED_ITEM.ITEM_ID, ITEM_NAME, RARITY
FROM UPGRADED_ITEM
JOIN ITEM_INFO ON UPGRADED_ITEM.ITEM_ID = ITEM_INFO.ITEM_ID
ORDER BY 1 DESC;