-- 코드를 입력하세요
-- SELECT MCDP_CD AS '진료과코드', COUNT(PT_NO) AS '5월예약건수'
-- FROM APPOINTMENT
-- WHERE (DATE_FORMAT(APNT_YMD, '%Y-%m-%d') BETWEEN '2022-05-01' AND '2022-05-31') AND APNT_CNCL_YN = 'N'
-- GROUP BY '진료과코드'
-- ORDER BY '5월예약건수' ASC


SELECT MCDP_CD AS '진료과코드', COUNT(*) AS '5월예약건수'
FROM APPOINTMENT
WHERE (DATE_FORMAT(APNT_YMD, '%Y-%m-%d') BETWEEN '2022-05-01' AND '2022-05-31')
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_NO), MCDP_CD


