SELECT MAX_SCORE.SCORE, HR_EMPLOYEES.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM 
    (SELECT HR_GRADE.EMP_NO, SUM(SCORE) AS SCORE
     FROM HR_GRADE
     WHERE YEAR = 2022
     GROUP BY 1
     ORDER BY 2 DESC
     LIMIT 1) AS MAX_SCORE,
    HR_DEPARTMENT,
    HR_EMPLOYEES
WHERE HR_EMPLOYEES.EMP_NO = MAX_SCORE.EMP_NO AND HR_EMPLOYEES.DEPT_ID = HR_DEPARTMENT.DEPT_ID
